### ISSUE TITLE
"Paging Example" is syntactically incorrect

### ISSUE THREAD

**Issue by sorenriise** [Factual/factual-nodejs-driver#4]
The example

    factual.get('/t/places-us', {q:"starbucks", filters:{"$or":[{"locality":{"$eq":"los angeles"}},{"locality":{"$eq":"santa monica"}}]}},
          offset:20, 
          limit:20, function (error, res) {
                               console.log(res.data);
                      });

has the offset and limit as parameters to the function -- the syntax used is not supported by JavaScript

**Comment by BradleyFactual** [comment]
updated.
