### ISSUE TITLE
how to do geotag?

### ISSUE THREAD

**Issue by capaj** [Factual/factual-nodejs-driver#6]
I tried:
```javascript
factual.get(`/geotag?latitude=${lat}&longitude=${long}`), function(){})
```

but that returns undefined. What is a proper way to call it?

**Comment by BradleyFactual** [comment]
The driver is intended for use with our older V3 APIs. Geotag is built on our new stack, which no longer requires OAuthentication. All you need to do is compose an HTTPS request, put your API key in the KEY parameter (API secret isn't used), and make your request.

**Comment by capaj** [comment]
@BradleyFactual thanks, I did it like that in the end
